data:
  dataset_names: [GOPRO_ours]
  top_k: 4500

  GOPRO_ours:
    images_path: /path/to/GOPRO_Large
    sequences_split_path: /path/to/datasets/GOPRO_sequences_split_ours
    labels_path: /path/to/GOPRO_raw_ground_truth_more_points
    patch_size: 256

  homographic:
    perspective: 0.2
    rotation: 25
    scale: 0.2
    
  train_batch_size: 16
  val_batch_size: 1

  train_num_workers: 16
  val_num_workers: 16

model:
  optimizer:
    name: adamw
    lr: 0.001
    weight_decay: 0.0005
    total_epochs: 60
    decay_step_list: [0.6, 0.8]
    warmup_epoch: 4
    lr_decay: 0.1
    lr_clip: 0.0000001
  scheduler:
    name: cosine
    start_epoch: 0
    min_lr: 0.000001
    decay_rate: 0.5
  early_stopping:
    enabled: true
    patience: 5
    min_delta: 0.0001
  anchor_loss: softmax
  unsuper_loss:
    downsample: 8
    image_shape: [256,256]
    correspond: 8
    usp_weight: 2.0
    position_weight: 1.0
    score_weight: 2.0
    rep_weight: 2.0
    uni_weight: 0.25
  repeatability_loss:
    weight: 1.0
  cell_size: 8
  nms_size: 15

ckpt_save_interval: 2
